### ISSUE TITLE
Lambda and function argument

### ISSUE THREAD

**Issue by snipervld** [Leushenko/C99-Lambda#1]
Is it possible to call macro fn(...) inside function call, i.e.

int count(int (*ptr)(int))
{
return ptr(1);
}

func(int,f,(void)
{
count(fn(int,(int x),{ return x+1;})); //is it possible?
})

**Comment by AlexCeleste** [comment]
Not directly, it'd mess up the nesting of `8blk` structures. But yes, you can do it _in_directly - you have to wrap the function call with the `_feN` or `_clN` macros:

```
_fe1(count, (int,(int x),{ return x+1;}) );
```

This should mean the same as the above, but it balances the hidden `8blk`s.
