### ISSUE TITLE
Closures

### ISSUE THREAD

**Issue by snipervld** [Leushenko/C99-Lambda#2]
how to use clusures or "cl" macro. I tried example for closures, but it doesn't work (0xc0000005 error).
If i understand correctly, cl returns structure, that consists of pointer to function and some variables, that "copy" from functions, where cl called. If i print variables from this structure, it correctly prints, but if i call function - it crash.
Ex. (also crash)
int x=6;
int (\* f)(int)=*(int ( \* \* )(int))&cl(int,(int y),((int,x)),{return _env->x+y;});

printf("%d",f(5));

Thanks
P.S. I test it on MinGW (C::B) and Android

**Comment by AlexCeleste** [comment]
The `cl` macro returns a struct consisting of the pointer to the function, and the variables closed over, yes. However, the implementation function needs to be able to get at the bound data (or it isn't a closure). That means it needs to take the pointer to itself as the first argument, so it can access that data. e.g.:

```
#include <stdio.h>
#include "c_lambda.h"

func(int, main,(void) {
    int x=6;
    void * clos = &cl(int,(int y),((int,x)),{ return _env->x+y; });

    int(** f)(void *, int) = clos;

    printf("%d\n", (*f)(clos, 5));
})
```

It looks like I actually forgot to document this in the Readme (remembered to talk about passing closures to higher-order functions, but not to tell people how to write higher-order functions in the first place... derp!).

Actually I could improve this a lot by changing `cl` to return a pointer, and adding macros to declare closure types...

**Comment by AlexCeleste** [comment]
I have changed the way closures work to make it much more straightforward. See [`cltest.c`](https://github.com/Leushenko/C99-Lambda/blob/master/cltest.c) for a new usage example. `cl` now returns a pointer to an object and it's much easier to use.
